### ISSUE TITLE
script doesn't find anything under 30€

### ISSUE THREAD

**Issue by scr44tch** [danielskowronski/hetzner-auction-hunter#1]
hi,

the script doesn't find anything under 30€
im looking for something cheap.

my command is:
hah.py --price 30 --disk-size 2000 --ram 16 --cpu-score 2000

i get results but only up from 30€, but on the site are a few listed for 24/25 €

**Comment by danielskowronski** [comment]
Ah, I see what may be the issue - it's tax rate which I assumed is 19% for Germany. 

It's selectable in top left corner. Can you verify that you see the same results if you choose Germany? If so I'll add tax rate as command line parameter.

**Comment by scr44tch** [comment]
its the tax.
price for US is set to 0% on the website,
when entering my country, its all working good.

thx for the fast reply
