### ISSUE TITLE
Script breaks if file contains any data

### ISSUE THREAD

**Issue by QreKer** [danielskowronski/hetzner-auction-hunter#4]
Hi, there one problem that must be fixed.
Sometimes script breaks if file already exists and contain any data.
It's can be fixed in both ways: 
1. importing os lib and adding after line 26 in `` if not args.test_mode: ``
Something like this:
`` if os.path.exists(file) ``
`` os.remove(file) ``
2. On line 28 `` f = open(file,'a+') `` 'a+' must be replaced with 'w+'

Both tested and working fine.

**Comment by danielskowronski** [comment]
The purpose of this state file is to keep track which servers were already processed and avoid sending notifications twice. 
So skipping any server with ID stored in state file is expected behaviour.
