### ISSUE TITLE
Telegram config container secret support

### ISSUE THREAD

**Issue by ITestInProd** [danielskowronski/hetzner-auction-hunter#8]
Currently telegram-send will only use the default configuration paths when executing via Python. When leveraging containers with secrets for the Telegram bot API keys this causes issues with remapping the secret to a configuration file inside of telegran-send's path.

Please add support for providing different configuration files outside of the default paths.

**Comment by ITestInProd** [comment]
Submitted pull #7

**Comment by danielskowronski** [comment]
Merged
